const navBar = document.getElementById('navBar');
navBar.setAttribute('id', 'socialNetworkNavigation');
const ul = navBar.querySelector('ul');
const newLi = document.createElement('li');
const textNode = document.createTextNode('Logout');
newLi.appendChild(textNode);
ul.appendChild(newLi);
const firstLi = ul.firstElementChild;
const lastLi = ul.lastElementChild;
console.log(`First element text: ${firstLi.textContent}`);
console.log(`Last element text: ${lastLi.textContent}`);
